### PR TITLE
Add dependency for web tests, add recommended extensions

### LINKED ISSUE #558: Automated tests not working
```sh
~/repos/vscode-autohotkey2-lsp (users/markwiemer/lint)
$ npm run chrome
2024-08-01 21:55:19

> vscode-autohotkey2-lsp@2.4.8 chrome
> vscode-test-web --browserType=chromium --extensionDevelopmentPath=. ./test-data      

'vscode-test-web' is not recognized as an internal or external command,
operable program or batch file.
[last: 1s]
~/repos/vscode-autohotkey2-lsp (users/markwiemer/lint)
$ npm i -D vscode-test-web
2024-08-01 21:55:29
npm error code ENOVERSIONS
npm error No versions available for vscode-test-web
npm error A complete log of this run can be found in: C:\Users\markw\AppData\Local\npm-cache\_logs\2024-08-02T04_55_30_113Z-debug-0.log
[last: 4s]
~/repos/vscode-autohotkey2-lsp (users/markwiemer/lint)
$
```

Is this an old, unused script, by chance? Are there any other plans to add automated tests for this repo?

### PR DESCRIPTION
**Pull request by mark-wiemer**
"@vscode/test-web": "^0.0.56"

This is the best dependency for running `vscode-test-web` and automatically validating each release.

This PR also adds recommended extensions so developers are using the best IDE tools available

Closes #558

### CODE REVIEW

**Comment by thqby** [comment]
I only used `@vscode/test-web` when adding web support and later removed it.

**Comment by mark-wiemer** [comment]
Yes, but I'd like to add unit tests to this repo to validate each release and ensure that new PRs don't break existing features, and @vscode/test-web is the best way to do that. You're welcome to refer to AHK++ to see how it works there :)

**Comment by thqby** [comment]
I use `@vscode/test-electron` to test the extension, which can use a locally installed vscode to start the test, avoiding downloading additional vscode or chrome browsers.

**Comment by mark-wiemer** [comment]
OK, so you have test-electron installed globally? That's fine, I just want to make sure so I open a reasonable PR moving forward. If there are any other global npm packages you use, documenting them would be helpful so that others can contribute

**Pull request closed without merging**
