### PR TITLE
Resolve package-lock issues and fix ESLint

### PR DESCRIPTION
**Pull request by mark-wiemer**
Ran `npm i -d eslint@^8.56.0` to resolve the ERESOLVE error. eslint@9.4.0 conflicts with eslint@^8.56.0 from typescript-eslint@7.12.0. The newest version of typescript-eslint has the same issue, so downgrading is the best option.

ESLint was not finding files (added `--debug` to confirm), you need to include a path, so I included `.` (the whole repo). This found some `while (true)` issues that I'm ignoring for now, you're welcome to remove this rule if you don't want it.

### CODE REVIEW

**Comment by thqby** [comment]
Although they conflict, I don't know how to successfully install them and work properly.

**Comment by thqby** [comment]
add the following to your package.json:
"overrides": { "eslint": "^9.4.0" }

**Comment by thqby** [comment]
> add the following to your package.json: "overrides": { "eslint": "^9.4.0" }

I have added this line to the package.json.
In addition, for the current version of eslint, `--report-unused-disable-directives --max-warnings 0` and `no-constant-condition=off` seem to be the default.

**Comment by mark-wiemer** [comment]
Coming back just to say this did resolve my issue :)

**Pull request closed without merging**
