### PR TITLE
Support for built-in functions

### PR DESCRIPTION
**Pull request by Axlefublr**
Now you can color built-in functions differently from user defined functions

image

If you don't, built-in functions will be colored as normal, no change there

I personally loved the option of this customizability back when I had it, I'm sure some people would appreciate it too

I've noticed that built-in methods and properties are not defined, I can make the regex for them too, but I have no idea where to put it in the tmLanguage file. If you'd be willing to merge that too (to then actually put it where it should be), I'd really appreciate it

Reply if you want me to do that

### CODE REVIEW

**Comment by thqby** [comment]
You don't need to change it, and it works the same way, depending on the theme.

Disable `Semantic Highlighting`
image

With `Semantic Highlighting` enabled, user-defined functions that have the same name as built-in functions can be recolor.
image

**Comment by Axlefublr** [comment]
As far as I understand, semantic highlighting off will let you color user defined functions differently. That is, if it actually *recognizes* what that function is in the first place. The amount of times I can't go to definition / see function parameters and all those sorts of issues is staggering. 

This built in method very easily may be something that's annoying to fix for the user, on the other hand, if there's a different class for built-in functions, that's one easy change that will *always* work, guaranteed. 

I think it's going to be easier comfortability-wise to just have a different class for built in functions

You surely aren't going to explain what you just did to me, to your every user, and this info isn't widely known

On the same hand, when someone watches a tutorial on how to color their code and they realize that built-in functions and normal ones are the same class, they will give up on trying to make it work

Plus, remember you having an issue with my previous pull request because of semantic highlighting off? "Theme defined" is the default, and since we can't know what the average user will have for that setting, we should go ahead and fix it for them

Essentially, it's one less feature. Just because something *can* be done, doesn't mean it's natural to do, and it's nice to give your users the comfortability of not having to know how to fix an issue, because you simply fixed it for them

**Comment by thqby** [comment]
built-in function's textmate scopes is `support.function`, other function's textmate scopes is `entity.name.function`.

**Comment by Axlefublr** [comment]
Yeah, that took me a long time to realize. For some reason, I thought they were the same, my bad.

Now for a different thing that *isn't* implemented yet lol

Built-in methods and properties

I can make the regex, would you add that? Would be great to color built in methods and properties differently too

**Comment by thqby** [comment]
>I've noticed that built-in methods and properties are not defined

This is unreliable, and the types of variables are variable.

**Comment by Axlefublr** [comment]
Oh, I guess that's true. Never mattered to me as long as I got the visual hint at what's what, but fair enough

**Pull request closed without merging**
